### ISSUE TITLE
Decide on which DB solution to use

### ISSUE THREAD

**Issue by edipetres** [Praqma/questionnaire-engine#127]
Mlab.com is our current built-in solution:
### Pros: 
- hosted db solution
- no need to create separate db image and connect to it
- free of charge - up to 0.5 GB database storage
### Cons:
- storage limit

## ToDo:
If we keep the current solution
- [ ] create a private submodule for configuration
- [ ] remove passwords from code
- [ ] move db url to configuration

**Comment by edipetres** [comment]
discussed with Bue in meeting today
