### ISSUE TITLE
Design decisions

### ISSUE THREAD

**Issue by edipetres** [Praqma/questionnaire-engine#143]
## To-do:
- [ ] Bue to create AWS account for deployment
- [ ] decide how to deploy services to ECS (remove service and add new or update?)
- [ ] namespace is in URL path - not as subdomain
- [ ] docker image versioning - should we use latest?
- [ ] is Docker run step necessary?
- [ ] * Choose deployment platform and domain routing 

_* In the last step in our pipeline, we spin up a server with the newly built container image which is assigned an IP. We want to have our domain (questionnaire.praqma.com) redirected to this new IP address. If we host the domain on Route 53 we can automatically have the load balancer redirect it.

**Comment by edipetres** [comment]
Discussed in our meeting with Bue today and issues have been created.
